// This file is auto-generated by vscode-router-generator
// Do not edit this file directly

// Page Routes
// "/songs/:id": Song
// "/songs/": Songs
// "/items/:id": Item
// "/items/": Items
// "/books/:id": Book
// "/books/": Books
// "/": Home

// ignore_for_file: prefer_const_constructors

import 'package:go_router/go_router.dart';

import 'routes/index.dart' as route6;
import 'routes/books/index.dart' as route5;
import 'routes/books/[id].dart' as route4;
import 'routes/items/index.dart' as route3;
import 'routes/items/[id].dart' as route2;
import 'routes/songs/index.dart' as route1;
import 'routes/songs/[id].dart' as route0;

final routes = <GoRoute>[
  GoRoute(
    path: '/',
    builder: (context, state) => route6.Home(),
    routes: <GoRoute>[
      GoRoute(
        path: 'songs',
        builder: (context, state) => route1.Songs(),
        routes: <GoRoute>[
          GoRoute(
            path: ':id',
            builder: (context, state) => route0.Song(
              id: state.params['id']!,
            ),
            routes: <GoRoute>[],
          ),
        ],
      ),
      GoRoute(
        path: 'items',
        builder: (context, state) => route3.Items(),
        routes: <GoRoute>[
          GoRoute(
            path: ':id',
            builder: (context, state) => route2.Item(
              id: state.params['id']!,
            ),
            routes: <GoRoute>[],
          ),
        ],
      ),
      GoRoute(
        path: 'books',
        builder: (context, state) => route5.Books(),
        routes: <GoRoute>[
          GoRoute(
            path: ':id',
            builder: (context, state) => route4.Book(
              id: state.params['id']!,
            ),
            routes: <GoRoute>[],
          ),
        ],
      ),
    ],
  ),
];

final router = GoRouter(
  routes: routes,
);
